test_script:
- go version
- go env
- set GOPATH=%APPVEYOR_BUILD_FOLDER%\gopath
- set PATH=%GOPATH%\bin;%PATH%
- go get -u github.com/golang/lint/golint
- go get github.com/sparrc/gdm
- gdm restore
  
build: off
